### ISSUE TITLE
Make native module Context Aware

### ISSUE THREAD

**Issue by bacelarhenrique** [skiptirengu/anitomy-js#18]
Hi,

Any chance of making the native module Context Aware to avoid problems with Electron?

**Comment by skiptirengu** [comment]
Hello,

I'm considering migrating to NAPI from NAN. I think this will fix any context related issues.

**Comment by bacelarhenrique** [comment]
I see.

Can I have a contact for further discussion?

**Comment by skiptirengu** [comment]
I've finished migration to the `node-addon-api`. Please take a look at the [develop](https://github.com/skiptirengu/anitomy-js/tree/develop) branch and see if the issue is fixed for you.

I need to update the docs, but I'll publish version `5.0` soon.

**Comment by bacelarhenrique** [comment]
In this case to test the develop branch on my node project do I have to build the project?

**Comment by skiptirengu** [comment]
No. Instead of using the npm registry, just add the dependency directly: `npm install github:skiptirengu/anitomy-js#develop`

**Comment by bacelarhenrique** [comment]
Works like a charm. Thanks a lot for the support.

Cheers!

**Comment by skiptirengu** [comment]
Published on NPM as version `5.0`.
